from dataclasses import dataclass, field
from enum import Enum
from typing import List, Tuple

class ToneType(str, Enum):
    FORMAL = "formal"
    CASUAL = "casual"
    AUTO = "auto"

@dataclass(frozen=True)
class AudioFrame:
    """Encapsulates raw binary audio data received from the client microphone."""
    data: bytes
    sample_rate: int = 16000
    channels: int = 1
    encoding: str = "linear16"

@dataclass(frozen=True)
class TranscriptSegment:
    """Represents a speech segment transcribed by the ASR system."""
    text: str
    is_final: bool
    confidence: float
    timestamp: float
    speech_final: bool = False

@dataclass(frozen=True)
class TranslationSegment:
    """Represents a translated text segment prepared for synthesis."""
    source_text: str
    translated_text: str
    tone: ToneType
    latency_ms: float

@dataclass(frozen=True)
class AudioOutputSegment:
    """Encapsulates binary audio generated by the TTS module for client playback."""
    audio_bytes: bytes
    content_type: str = "audio/mpeg"
    associated_text: str = ""

@dataclass
class SessionContext:
    """Manages the state and conversation context of a single client pipeline connection."""
    session_id: str
    history: List[Tuple[TranscriptSegment, TranslationSegment]] = field(default_factory=list)
    default_tone: ToneType = ToneType.FORMAL
    is_active: bool = True

    def add_turn(self, transcript: TranscriptSegment, translation: TranslationSegment) -> None:
        self.history.append((transcript, translation))

    def determine_tone(self) -> ToneType:
        """Heuristic to evaluate tone based on historical inputs."""
        # Custom business rules can be added here
        return self.default_tone
